Create AddRemoveCartTest
shibiza/group_3 pull request #1
Opened 2022-08-19 15:45 UTC by Petr-Kv

I look forward to your suggestions for improving the code, I will be glad to any comments.

2022-08-20 21:33 UTC, sabinawozniak requested changes, later dismissed

2022-08-20 21:33 UTC, sabinawozniak commented on src/test/java/org/example/AddRemoveCartTest
> +                "D:\\Git\\practicMaventest1\\src\\test\\resources\\webdriver\\chromedriver.exe");
try to use dependency from today's lesson. this might not work on another computer.

2022-08-21 13:34 UTC, RoboPen commented
Use nouns to name variables, not verbs. Verbs are reseved for methods. Also try to describe elements more precisely. Variable names like "addInformationLabel" or "addInformationLabel2" dont tell you much. Try to get rid of repetitive code by using @BeforeTest or @BeforeMethod

2022-08-22 09:12 UTC, shibiza commented
Hello! You may try to use not just @Test annotation, but also @BeforeMethod and @AfterMethod. Just have a look as I do it at my branch https://github.com/shibiza/group_3/tree/delivery_to_functionality

By the way as I can see you had just 2 tests (2 methods):    public void addCart()  and  public void deleteCart(), so please try to use my advise and expand your list of used annotations

2022-08-22 13:49 UTC, shibiza commented
and you know that's strange... but your class AddRemoveCartTest doesn't have ".java" and your code doesn't want to compilate in my Intelijy because of that. I can read your code only in github. It's better to fix that ASAP

2022-08-22 17:29 UTC, mat-kud commented
Lines #26 and #34, you still use verbs to describe variable

2022-08-22 18:23 UTC, shibiza commented
sorry but you did it wrong. Read carefully how to name java.classes and where to store them. It was on our lecture. None of your @Test works

2022-08-22 21:14 UTC, Petr-Kv commented on src/test/java/org/example/AddRemoveCartTest
> +                "D:\\Git\\practicMaventest1\\src\\test\\resources\\webdriver\\chromedriver.exe");
fixed

2022-08-22 21:19 UTC, sabinawozniak approved these changes

2022-08-23 07:24 UTC, shibiza approved these changes

2022-08-23 11:32 UTC, RoboPen approved these changes

2022-08-27 20:20 UTC, juliaHrabovska commented on src/test/java/org/example/AddRemoveCartTest.java
> +        Assert.assertEquals("1", checkInformationLabelCart.getText());
It would be better to add a string with the explanation of what is expected

2022-08-27 20:25 UTC, merged