Filtering and searching functionality1
shibiza/group_3 pull request #6
Opened 2022-08-21 15:31 UTC by RoboPen

There are problems with grabbing products prices, because of sponsored products

2022-08-21 21:40 UTC, sabinawozniak requested changes
Test verifyTitlesContainChosenBrand failed (maybe only on my computer, because I don't see "Corsair" on the main page): Unable to locate element: {"method":"xpath","selector":"//span[text() = 'Corsair']"}
I think that if you will add action which click "See more", then this test will pass.
And I think that you can use only the second Data Provider and use only this data which you need in the first test (only "Corsair"). It's just a suggestion - your code is ok.

2022-08-22 09:23 UTC, shibiza commented
Hello! As I can see 

 WebElement brandNameCheckbox = webDriver.findElement(By.xpath("//span[text() = '" + brandName + "']"));

you use triple times in each of your 3 tests, so you may add this variable to your class, not inside @test method

2022-08-22 17:01 UTC, RoboPen commented
After asking driver to expand brand list, it doesnt want to iterate over pages

2022-08-22 18:18 UTC, shibiza commented
You know, the process finished with exit code -1. No one of your @Test works...

2022-08-22 20:01 UTC, Petr-Kv submitted a review, later dismissed

2022-08-22 20:09 UTC, RoboPen commented
There is a problem with verifyProductsPricesAreSorted test. I found "hidden" products in DOM structure. Thats why test fails

2022-08-22 22:21 UTC, sabinawozniak requested changes

2022-08-22 22:21 UTC, sabinawozniak commented on src/test/java/org/example/FilteringAndSearchingTest.java
> +            arePricesInChosenRange = webDriver.findElements(By.xpath("//span[@class=\"a-price\"]/span[@class=\"a-offscreen\"]"))
Your xpath finds elements from outside of results list which gives me false negative test result.

![image](https://user-images.githubusercontent.com/100229236/186028464-436dd14f-f368-4a77-ae42-06702dcc2f74.png)

2022-08-22 22:28 UTC, sabinawozniak commented on src/test/java/org/example/FilteringAndSearchingTest.java
> +            arePricesInChosenRange = webDriver.findElements(By.xpath("//span[@class=\"a-price\"]/span[@class=\"a-offscreen\"]"))
Oh sorry, I didn't see your previous comment, that you just found what is wrong ;) I hope that you will deal with this problem.

2022-08-23 07:19 UTC, shibiza approved these changes

2022-08-23 13:04 UTC, sabinawozniak approved these changes

2022-08-23 13:04 UTC, sabinawozniak commented on src/test/java/org/example/FilteringAndSearchingTest.java
> +    public void verifyProductsPricesAreInDefinedRange(String brandName, float minPrice, float maxPrice) {
![image](https://user-images.githubusercontent.com/100229236/186164863-16696e16-9d0e-4833-843d-2ec37e5e42a9.png)

![image](https://user-images.githubusercontent.com/100229236/186164741-f937fcab-e46a-4219-bffd-5430f021c939.png)

2022-08-23 13:04 UTC, sabinawozniak commented on src/test/java/org/example/FilteringAndSearchingTest.java
> +    public void verifyProductsPricesAreSortedAscendingly(String brandName) {
Same as above test

2022-08-23 13:19 UTC, RoboPen commented
Test fails as expected, because conditions are not met. Try to commend after method and check it out by yourself

2022-08-23 13:42 UTC, Petr-Kv commented
![image](https://user-images.githubusercontent.com/107186284/186173655-17562f68-0a26-49fe-a0cc-069dc7e965eb.png)

Yes, you are right

2022-08-23 13:44 UTC, Petr-Kv approved these changes

2022-08-27 20:53 UTC, juliaHrabovska commented on src/test/java/org/example/FilteringAndSearchingTest.java
> +    /*@AfterTest
Commented code shouldn't be in the code you push to a remote repo

2022-08-27 21:03 UTC, juliaHrabovska commented on src/test/java/org/example/FilteringAndSearchingTest.java
> +            everyTitleContainsInputWord = webDriver.findElements(By.xpath("//div[contains(@class,'s-card-container')]//span[contains(@class,'a-size-medium')]"))
It is better to make this line shorter. Just move some parts to the next line. The same for other

2022-08-27 21:03 UTC, juliaHrabovska commented on src/test/java/org/example/FilteringAndSearchingTest.java
> +
Extra lines

2022-08-28 08:00 UTC, merged